### ISSUE TITLE
Some nested f-strings with double quotes are not converted

### ISSUE THREAD

**Issue by cioma** [JarryShaw/f2format#3]
It seems that some nested f-strings with double quotes are not converted. For example:

```
# Code:
logger.debug(f'[{", ".join([f"0x{item:04X}" for item in data])}]')

# Gets converted to:
logger.debug('[{}]'.format(", ".join([f"0x{item:04X}" for item in data])))

# Code:
logger.error(f'FAIL: Wrong response to an invalid command 0x{command:02X} from FTDI device, port {port}: [{", ".join([f"0x{item:02X}" for item in data_r])}]')

# Gets converted to:
logger.error('FAIL: Wrong response to an invalid command 0x{:02X} from FTDI device, port {}: [{}]'.format(command, port, ", ".join([f"0x{item:02X}" for item in data_r])))
```
See code in the attachment

I'm running the latest f2format from Git under Python 3.6.5.
[ftdi.py.zip](https://github.com/JarryShaw/f2format/files/3186694/ftdi.py.zip)

**Comment by JarryShaw** [comment]
Thx @cioma for reporting.

@gousaiyang has reported this bug and added the test cases (which is why CI is failing). We will get onto it soon.

But before we could fix it, please consider avoid using this grammar in your code. :)

**Comment by cioma** [comment]
Thank @JarryShaw!
Yes, I'll try not to use it. It's that I already have quite some code with multiple places like that which was written for v3.6 but now needs to work in v3.5 (but in years ahead hopefully we'll actually switch to v3.6)

**Comment by JarryShaw** [comment]
Ah... it just came across my mind that for texted f-strings, you can run `f2format` twice or more on that specific file or folder.

ps: sorry was a bit irritated w/ some other projects these days, will fix it in a short future :)

**Comment by cioma** [comment]
Wow! Indeed! Great idea, will try it soon :)

**Comment by cioma** [comment]
I can confirm that running a second time to deal with nested f-string works fine for me.
Many thanks for the suggestion @JarryShaw!

**Comment by JarryShaw** [comment]
We're happily announcing that this issue has been resolved 🎉 

Thx @cioma for reporting and using this tool~ (≧▽≦)
